[phases]
build = "python manage.py collectstatic --noinput"

[start]
cmd = "gunicorn gestion_citas.wsgi:application --bind 0.0.0.0:$PORT" # Asegúrate de que esto coincida con tu comando de inicio real, incluyendo bind y PORT si es necesario
