# Generated by Django 5.2 on 2025-05-10 14:27

import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antecedentes', models.TextField(blank=True)),
                ('medicamentos', models.TextField(blank=True)),
                ('alergias', models.TextField(blank=True)),
                ('observaciones', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='FotoTratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='tratamientos/')),
                ('descripcion', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('historia_clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='citas.historiaclinica')),
            ],
        ),
        migrations.CreateModel(
            name='Odontologo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('especialidad', models.CharField(max_length=100)),
                ('clinica_asignada', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='citas.clinica')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HorarioAtencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(help_text='1=Lunes ... 7=Domingo')),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citas.clinica')),
                ('odontologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citas.odontologo')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento_id', models.CharField(max_length=10, unique=True, verbose_name='Cédula o Documento')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('pais', django_countries.fields.CountryField(max_length=2)),
                ('telefono', models.CharField(help_text='Escribe el número sin el código del país. Ej: 3001234567', max_length=20)),
                ('clinica_creacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='citas.clinica')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='paciente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='citas.paciente'),
        ),
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('duracion', models.IntegerField(help_text='Duración en minutos')),
                ('especialidad_requerida', models.ForeignKey(help_text='Especialidad del profesional que realiza el tratamiento', null=True, on_delete=django.db.models.deletion.SET_NULL, to='citas.especialidad', verbose_name='Especialidad Requerida')),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('motivo_consulta', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('P', 'Pendiente'), ('T', 'Terminada')], default='P', max_length=1)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citas.clinica')),
                ('odontologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citas.odontologo')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citas.paciente')),
                ('tratamiento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='citas.tratamiento')),
            ],
        ),
    ]
