# Generated by Django 5.2 on 2025-04-23 22:38

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_fototratamiento_historiaclinica'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='documento_id',
            field=models.CharField(default='0000000000', max_length=10, unique=True, verbose_name='Cédula o Documento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='pais',
            field=django_countries.fields.CountryField(default='CO', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefono',
            field=models.CharField(help_text='Escribe el número sin el código del país. Ej: 3001234567', max_length=20),
        ),
    ]
