# Generated by Django 5.2 on 2025-05-11 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_alter_odontologo_especialidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='cabina',
            field=models.IntegerField(choices=[(1, 'Cabina 1'), (2, 'Cabina 2'), (3, 'Cabina 3')], default=1),
        ),
    ]
