# Generated by Django 5.2 on 2025-04-25 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0005_remove_odontologo_usuario_odontologo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='atendida',
            field=models.BooleanField(default=False),
        ),
    ]
