# Generated by Django 5.2 on 2025-04-25 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0006_cita_atendida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='atendida',
        ),
        migrations.AddField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('P', 'Pendiente'), ('T', 'Terminada')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='cita',
            name='motivo_consulta',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cita',
            name='tratamiento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='citas.tratamiento'),
        ),
    ]
