# Generated by Django 5.2 on 2025-04-29 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0007_remove_cita_atendida_cita_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fototratamiento',
            name='paciente',
        ),
        migrations.AddField(
            model_name='fototratamiento',
            name='historia_clinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='citas.historiaclinica'),
        ),
    ]
