# Generated by Django 5.2 on 2025-04-30 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0008_remove_fototratamiento_paciente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fototratamiento',
            name='historia_clinica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='citas.historiaclinica'),
        ),
    ]
