# Generated by Django 5.2 on 2025-05-07 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0011_alter_paciente_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='horarioatencion',
            name='odontologo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='citas.odontologo'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='odontologo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='citas.odontologo'),
        ),
        migrations.AddField(
            model_name='cita',
            name='clinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='citas.clinica'),
        ),
        migrations.AddField(
            model_name='horarioatencion',
            name='clinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='citas.clinica'),
        ),
        migrations.AddField(
            model_name='odontologo',
            name='clinica_asignada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='citas.clinica'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='clinica_creacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='citas.clinica'),
        ),
    ]
