# Generated by Django 5.2 on 2025-05-07 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0012_clinica_horarioatencion_odontologo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='clinica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citas.clinica'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='odontologo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citas.odontologo'),
        ),
        migrations.AlterField(
            model_name='horarioatencion',
            name='clinica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citas.clinica'),
        ),
        migrations.AlterField(
            model_name='horarioatencion',
            name='odontologo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citas.odontologo'),
        ),
        migrations.AlterField(
            model_name='odontologo',
            name='clinica_asignada',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='citas.clinica'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='clinica_creacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='citas.clinica'),
        ),
    ]
