# Generated by Django 5.2 on 2025-05-08 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0013_alter_cita_clinica_alter_cita_odontologo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='nombre',
        ),
        migrations.AddField(
            model_name='paciente',
            name='apellidos',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='nombres',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
