# Generated by Django 5.2 on 2025-05-09 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0014_remove_paciente_nombre_paciente_apellidos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tratamiento',
            name='especialidad_requerida',
            field=models.CharField(choices=[('Higienista', 'Higienista'), ('Odontología general', 'Odontología general'), ('Cirugía oral y maxilofacial', 'Cirugía oral y maxilofacial'), ('Endodoncia', 'Endodoncia'), ('Odontología estética', 'Odontología estética'), ('Odontopediatría', 'Odontopediatría'), ('Ortodoncia', 'Ortodoncia'), ('Patología bucal', 'Patología bucal'), ('Periodoncia', 'Periodoncia')], default='Odontología general', help_text='Especialidad del profesional que realiza el tratamiento', max_length=50),
        ),
    ]
